---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ncbiBlastR

<!-- badges: start -->
<!-- badges: end -->

The goal of ncbiBlastR is to ...

## Installation

You can install the development version of ncbiBlastR from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("thehung92/ncbiBlastR")
```

## Submit a sequence for NCBI blast

```{r example, eval=FALSE}
library(ncbiBlastR)
## the blast_api_wrapper
res = blast_api_wrapper(rbcLseq)
# it will run blast on NCBI first
# the program will check if there are no hit. then run blastn next
## extract the table from the response in HTML format with function
res |>
  extract_table_fromGET()
```

Example input and output data

```{r}
library(ncbiBlastR)
# sequence to submit
rbcLseq
# table from request
rbcLres |>
  extract_table_fromGET()
```

## current structure of the library

```mermaid
graph TD;
    A-->B;
    A-->C;
    B-->D;
    C-->D;
```
